import { useMemo } from 'react'
import {
  EuiModal,
  EuiModalHeader,
  EuiModalHeaderTitle,
  EuiModalBody,
  EuiModalFooter,
  EuiButton,
  EuiButtonEmpty,
  EuiFlexGroup,
  EuiFlexItem,
  EuiText,
  EuiCallOut,
  EuiSpacer,
  EuiCodeBlock,
  EuiButtonGroup,
} from '@elastic/eui'
import { useState } from 'react'
import { generateConfig } from '../../lib/logstash-generator'
import { useBuilderStore, useActivePipeline, DEFAULT_PIPELINE_SETTINGS } from '../../store/useBuilderStore'
import type { PipelineSettings } from '../../store/useBuilderStore'

function generatePipelinesYml(pipelineName: string, settings: PipelineSettings): string {
  const id = pipelineName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
  const lines = [
    '# Generated by Logstash Config Builder',
    '# Paste into /etc/logstash/pipelines.yml',
    '',
    `- pipeline.id: ${id}`,
    `  path.config: "/etc/logstash/conf.d/${id}.conf"`,
    `  pipeline.workers: ${settings.workers}`,
    `  pipeline.batch.size: ${settings.batchSize}`,
    `  pipeline.batch.delay: ${settings.batchDelay}`,
  ]
  if (settings.ordered !== 'auto') lines.push(`  pipeline.ordered: ${settings.ordered}`)
  if (settings.queueType !== 'memory') lines.push(`  queue.type: ${settings.queueType}`)
  lines.push('')
  return lines.join('\n')
}

function downloadText(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

type Tab = 'conf' | 'pipelines'

export function ConfigPreviewModal({ onClose }: { onClose: () => void }) {
  const { logstashVersion } = useBuilderStore()
  const pipeline = useActivePipeline()
  const [tab, setTab] = useState<Tab>('conf')

  const { config, keystoreVars, plaintextSecretWarnings } = useMemo(
    () => generateConfig({ pipelineName: pipeline.name, inputs: pipeline.inputs, filters: pipeline.filters, outputs: pipeline.outputs }, logstashVersion),
    [pipeline, logstashVersion]
  )

  const pipelinesYml = useMemo(
    () => generatePipelinesYml(pipeline.name, { ...DEFAULT_PIPELINE_SETTINGS, ...pipeline.settings }),
    [pipeline.name, pipeline.settings]
  )

  const content = tab === 'conf' ? config : pipelinesYml
  const filename = tab === 'conf' ? `${pipeline.name.toLowerCase().replace(/\s+/g, '-')}.conf` : 'pipelines.yml'

  return (
    <EuiModal onClose={onClose} style={{ width: 720, maxWidth: '95vw' }}>
      <EuiModalHeader>
        <EuiModalHeaderTitle>
          <EuiFlexGroup gutterSize="m" alignItems="center" responsive={false}>
            <EuiFlexItem>
              Export pipeline: <strong>{pipeline.name}</strong>
            </EuiFlexItem>
            <EuiFlexItem grow={false}>
              <EuiButtonGroup
                legend="File type"
                idSelected={tab}
                onChange={(id) => setTab(id as Tab)}
                options={[
                  { id: 'conf', label: 'logstash.conf' },
                  { id: 'pipelines', label: 'pipelines.yml' },
                ]}
                buttonSize="compressed"
              />
            </EuiFlexItem>
          </EuiFlexGroup>
        </EuiModalHeaderTitle>
      </EuiModalHeader>

      <EuiModalBody>
        {tab === 'conf' && plaintextSecretWarnings.length > 0 && (
          <>
            <EuiCallOut
              title={`${plaintextSecretWarnings.length} secret field(s) are in plaintext`}
              color="warning"
              iconType="lock"
              size="s"
            >
              <EuiText size="xs">
                <p>
                  Move these to the Logstash keystore:{' '}
                  <strong>{plaintextSecretWarnings.join(', ')}</strong>
                </p>
              </EuiText>
            </EuiCallOut>
            <EuiSpacer size="s" />
          </>
        )}

        {tab === 'conf' && keystoreVars.length > 0 && (
          <>
            <EuiCallOut
              title={`${keystoreVars.length} keystore variable(s) required`}
              color="primary"
              iconType="key"
              size="s"
            >
              <EuiText size="xs">
                <p>Run <code>bin/logstash-keystore add {keystoreVars.join(' ')}</code> before starting Logstash.</p>
              </EuiText>
            </EuiCallOut>
            <EuiSpacer size="s" />
          </>
        )}

        <EuiCodeBlock
          language={tab === 'conf' ? 'ruby' : 'yaml'}
          isCopyable
          overflowHeight={420}
          fontSize="s"
          paddingSize="m"
        >
          {content}
        </EuiCodeBlock>
      </EuiModalBody>

      <EuiModalFooter>
        <EuiFlexGroup justifyContent="spaceBetween" responsive={false}>
          <EuiFlexItem grow={false}>
            <EuiButtonEmpty onClick={onClose}>Close</EuiButtonEmpty>
          </EuiFlexItem>
          <EuiFlexItem grow={false}>
            <EuiButton
              iconType="download"
              fill
              onClick={() => downloadText(filename, content)}
            >
              Download {filename}
            </EuiButton>
          </EuiFlexItem>
        </EuiFlexGroup>
      </EuiModalFooter>
    </EuiModal>
  )
}
