import { useState } from 'react'
import {
  EuiHeader,
  EuiHeaderLogo,
  EuiButtonIcon,
  EuiButton,
  EuiButtonEmpty,
  EuiToolTip,
  EuiTabs,
  EuiTab,
  EuiFlexGroup,
  EuiFlexItem,
  EuiSuperSelect,
  EuiPopover,
  EuiContextMenuPanel,
  EuiContextMenuItem,
} from '@elastic/eui'
import { useBuilderStore, useActivePipeline, DEFAULT_PIPELINE_SETTINGS } from '../../store/useBuilderStore'
import type { PipelineSettings } from '../../store/useBuilderStore'
import { VERSIONS } from '../../lib/logstash-versions'
import { generateConfig } from '../../lib/logstash-generator'

function downloadText(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function generatePipelinesYml(pipelineName: string, settings: PipelineSettings): string {
  const id = pipelineName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
  const lines = [
    '# Generated by Logstash Config Builder',
    '# Paste into /etc/logstash/pipelines.yml',
    '',
    `- pipeline.id: ${id}`,
    `  path.config: "/etc/logstash/conf.d/${id}.conf"`,
    `  pipeline.workers: ${settings.workers}`,
    `  pipeline.batch.size: ${settings.batchSize}`,
    `  pipeline.batch.delay: ${settings.batchDelay}`,
  ]
  if (settings.ordered !== 'auto') lines.push(`  pipeline.ordered: ${settings.ordered}`)
  if (settings.queueType !== 'memory') lines.push(`  queue.type: ${settings.queueType}`)
  lines.push('')
  return lines.join('\n')
}

export function Toolbar({ onHome, onAIBuild }: { onHome?: () => void; onAIBuild?: () => void }) {
  const {
    logstashVersion,
    darkMode,
    toggleDarkMode,
    setShowTemplates,
    setShowImport,
    setShowGrok,
    setShowPreview,
    setLogstashVersion,
  } = useBuilderStore()
  const pipeline = useActivePipeline()

  const [downloadOpen, setDownloadOpen] = useState(false)

  const versionOptions = VERSIONS.map(v => ({
    value: v,
    inputDisplay: `Logstash ${v}`,
  }))

  const handleDownloadConf = () => {
    const { config } = generateConfig(
      { pipelineName: pipeline.name, inputs: pipeline.inputs, filters: pipeline.filters, outputs: pipeline.outputs },
      logstashVersion
    )
    const filename = `${pipeline.name.toLowerCase().replace(/\s+/g, '-')}.conf`
    downloadText(filename, config)
    setDownloadOpen(false)
  }

  const handleDownloadPipelinesYml = () => {
    const settings = { ...DEFAULT_PIPELINE_SETTINGS, ...pipeline.settings }
    downloadText('pipelines.yml', generatePipelinesYml(pipeline.name, settings))
    setDownloadOpen(false)
  }

  return (
    <EuiHeader
      position="fixed"
      sections={[
        {
          items: [
            onHome && (
              <EuiToolTip key="home-tip" content="Back to home">
                <EuiButtonEmpty
                  key="home"
                  iconType="arrowLeft"
                  size="s"
                  color="text"
                  onClick={onHome}
                >
                  Home
                </EuiButtonEmpty>
              </EuiToolTip>
            ),
            <EuiHeaderLogo key="logo" iconType="logoLogstash">
              Logstash Builder
            </EuiHeaderLogo>,
          ].filter(Boolean),
        },
        {
          items: [
            <EuiFlexGroup key="actions" gutterSize="s" alignItems="center" responsive={false}>
              {/* Version selector — EuiSuperSelect opens downward as a popover */}
              <EuiFlexItem grow={false}>
                <EuiSuperSelect
                  compressed
                  valueOfSelected={logstashVersion}
                  onChange={setLogstashVersion}
                  options={versionOptions}
                  popoverProps={{ anchorPosition: 'downRight' }}
                  style={{ minWidth: 140 }}
                />
              </EuiFlexItem>

              {/* AI Build button */}
              {onAIBuild && (
                <EuiFlexItem grow={false}>
                  <EuiButton
                    iconType="sparkles"
                    size="s"
                    color="accent"
                    onClick={onAIBuild}
                  >
                    AI Build
                  </EuiButton>
                </EuiFlexItem>
              )}

              <EuiFlexItem grow={false}>
                <EuiButtonEmpty iconType="importAction" size="s" onClick={() => setShowImport(true)}>
                  Import
                </EuiButtonEmpty>
              </EuiFlexItem>

              <EuiFlexItem grow={false}>
                <EuiButtonEmpty iconType="document" size="s" onClick={() => setShowTemplates(true)}>
                  Templates
                </EuiButtonEmpty>
              </EuiFlexItem>

              {/* Preview button */}
              <EuiFlexItem grow={false}>
                <EuiButtonEmpty iconType="eye" size="s" onClick={() => setShowPreview(true)}>
                  Preview
                </EuiButtonEmpty>
              </EuiFlexItem>

              {/* Download dropdown */}
              <EuiFlexItem grow={false}>
                <EuiPopover
                  isOpen={downloadOpen}
                  closePopover={() => setDownloadOpen(false)}
                  button={
                    <EuiButton
                      iconType="download"
                      iconSide="left"
                      size="s"
                      fill
                      onClick={() => setDownloadOpen(o => !o)}
                    >
                      Download
                    </EuiButton>
                  }
                  panelPaddingSize="none"
                  anchorPosition="downRight"
                >
                  <EuiContextMenuPanel
                    items={[
                      <EuiContextMenuItem
                        key="conf"
                        icon="document"
                        onClick={handleDownloadConf}
                      >
                        logstash.conf
                      </EuiContextMenuItem>,
                      <EuiContextMenuItem
                        key="yml"
                        icon="list"
                        onClick={handleDownloadPipelinesYml}
                      >
                        pipelines.yml
                      </EuiContextMenuItem>,
                    ]}
                  />
                </EuiPopover>
              </EuiFlexItem>

              <EuiFlexItem grow={false}>
                <EuiButton iconType="bug" size="s" onClick={() => setShowGrok(true)} color="text">
                  Grok Debugger
                </EuiButton>
              </EuiFlexItem>

              <EuiFlexItem grow={false}>
                <EuiToolTip content={darkMode ? 'Switch to light mode' : 'Switch to dark mode'}>
                  <EuiButtonIcon
                    iconType={darkMode ? 'sun' : 'moon'}
                    onClick={toggleDarkMode}
                    aria-label="Toggle dark mode"
                    color="text"
                  />
                </EuiToolTip>
              </EuiFlexItem>
            </EuiFlexGroup>,
          ],
        },
      ]}
    />
  )
}

export function PipelineTabs({ onOpenSettings }: { onOpenSettings: () => void }) {
  const { pipelines, activePipelineId, setActivePipeline, addPipeline } = useBuilderStore()

  return (
    <div style={{
      borderBottom: '1px solid var(--euiBorderColor)',
      background: 'var(--euiPageBackgroundColor)',
      paddingTop: 48,
    }}>
      <EuiFlexGroup gutterSize="none" alignItems="center" responsive={false}>
        <EuiFlexItem>
          <EuiTabs size="s" style={{ paddingLeft: 12 }}>
            {pipelines.map(p => (
              <EuiTab
                key={p.id}
                isSelected={p.id === activePipelineId}
                onClick={() => setActivePipeline(p.id)}
              >
                {p.name}
              </EuiTab>
            ))}
          </EuiTabs>
        </EuiFlexItem>
        <EuiFlexItem grow={false} style={{ paddingRight: 4 }}>
          <EuiToolTip content="Pipeline settings">
            <EuiButtonIcon
              iconType="gear"
              onClick={onOpenSettings}
              aria-label="Pipeline settings"
              color="text"
              size="s"
            />
          </EuiToolTip>
        </EuiFlexItem>
        <EuiFlexItem grow={false} style={{ paddingRight: 8 }}>
          <EuiToolTip content="Add pipeline">
            <EuiButtonIcon
              iconType="plusInCircle"
              onClick={addPipeline}
              aria-label="Add pipeline"
              color="text"
              size="s"
            />
          </EuiToolTip>
        </EuiFlexItem>
      </EuiFlexGroup>
    </div>
  )
}
